---
- name: Check VM existence in physical servers
  include_tasks: check_virtual_server_existance.yaml
  with_items: "{{ groups['physical_servers'] }}"
  vars: 
    not_existing_vm: []
    existing_vm: []
  loop_control:
    loop_var: physical_server_item

- name: Print VM to deploy
  debug:
    msg: "{{ item }}"
  with_items: "{{ not_existing_vm }}"
  when: not_existing_vm is defined

- name: Prompt to confirm
  pause:
    prompt: Please confirm you want to create specified VM. Press return to continue. Press Ctrl+c and then "a" to abort

- name: Initialize and start {{ item }} virtual server
  shell: lxc launch images:ubuntu/focal/cloud "{{ hostvars[item]['inventory_hostname'] }}" --vm --storage kubernetes --profile {{ hostvars[item]['resources']['profile'] }} --config limits.cpu={{ hostvars[item]['resources']['cpus'] }} --config limits.memory={{ hostvars[item]['resources']['memory'] }} --network br-eno1
  with_items: "{{ not_existing_vm }}"
  when: not_existing_vm is defined

- name: Configure newly created VM
  include_tasks: configure_virtual_server.yaml
  with_items: "{{ groups['virtual_servers'] }}"