---
- name: Install and configure Multipass and dependencies
  import_tasks: multipass_install.yaml

- name: Configure multipass on physical hosts
  import_tasks: configure_physical_server.yaml
  tags:
    - always

- name: Purge virtual servers
  import_tasks: purge_virtual_server.yaml
  tags:
    - purge_vm
    - never

- name: Purge profiles
  import_tasks: purge_lxd_profiles.yaml
  tags:
    - purge_vm
    - never

- name: Create needed profiles
  import_tasks: create_lxd_profiles.yaml
  tags:
    - create_vm
    - never

- name: Deploy virtual servers
  import_tasks: deploy_virtual_server.yaml
  tags:
    - create_vm
    - never