---
- name: Check VM existence in physical servers
  include_tasks: check_virtual_server_existance.yaml
  with_items: "{{ groups['physical_servers'] }}"
  vars:
    not_existing_vm: []
    existing_vm: []
  loop_control:
    loop_var: physical_server_item

- name: Print VM to purge
  debug:
    msg: "{{ item }} will be deleted"
  with_items: "{{ existing_vm }}"
  when: existing_vm is defined

- name: Prompt to confirm
  pause:
    prompt: Please confirm you want to delete specified VM. Press return to continue. Press Ctrl+c and then "a" to abort

- name: Purge VM
  shell: lxc stop "{{ hostvars[item]['inventory_hostname'] }}"
  with_items: "{{ existing_vm }}"
  when: existing_vm is defined
  ignore_errors: true

- name: Purge VM
  shell: lxc delete "{{ hostvars[item]['inventory_hostname'] }}"
  with_items: "{{ existing_vm }}"
  when: existing_vm is defined